name: sst deploy

on:
  # pull_request:
  #   branches:
  #     - main
  #     - stage
  #     - dev
  #   types:
  #     - closed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  set-stage-name:
    runs-on: ubuntu-latest
    outputs:
      stage_name: ${{ steps.set-stage.outputs.stage_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set stage name
        id: set-stage
        run: |
          if [ "${GITHUB_REF#refs/heads/}" = "main" ]; then
            echo "stage_name=prod" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF#refs/heads/}" = "stage" ]; then
            echo "stage_name=stage" >> $GITHUB_OUTPUT
          else
            echo "stage_name=dev" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: set-stage-name
    runs-on: ubuntu-latest
    environment: ${{ needs.set-stage-name.outputs.stage_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ASSUME_ROLE_NAME }}"
          aws-region: ap-northeast-1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install npm packages
        run: npm install

      - name: SST Deploy
        run: npx sst deploy --stage ${{ needs.set-stage-name.outputs.stage_name }}
