name: sst deploy

on:
  # pull_request:
  #   branches:
  #     - main
  #     - stage
  #     - dev
  #   types:
  #     - closed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ASSUME_ROLE_NAME }}"
          aws-region: ap-northeast-1

  sst-deploy:
    needs: aws-login
    runs-on: ubuntu-latest
    steps:
      - name: set stage name
        run: |
          if [ "${GITHUB_REF#refs/heads/}" = "main" ]; then
            echo "STAGE_NAME=prod" >> $GITHUB_ENV
          else
            echo "STAGE_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install npm packages
        run: npm install

      - name: sst deploy
        run: npx sst deploy --stage $STAGE_NAME
